# Generated by Django 5.0.7 on 2026-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin/Staff'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=20),
        ),
    ]
