# Generated by Django 5.0.7 on 2026-04-01 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_laporan', models.DateField(auto_now_add=True, verbose_name='Waktu Pembuatan')),
                ('periode', models.CharField(max_length=50, unique=True, verbose_name='Periode Laporan')),
                ('tanggal_mulai', models.DateField(verbose_name='Dari Tanggal')),
                ('tanggal_akhir', models.DateField(verbose_name='Sampai Tanggal')),
                ('total_transaksi', models.IntegerField(default=0, editable=False)),
                ('pendapatan_cash', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('pendapatan_transfer', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Tersedia', max_length=50)),
                ('stok', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pesanan', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status_bayar', models.CharField(choices=[('Menunggu Konfirmasi', 'Menunggu Konfirmasi'), ('Sedang Diproses', 'Sedang Diproses'), ('Dikirim', 'Dikirim'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Menunggu Konfirmasi', max_length=50)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metode_pembayaran', models.CharField(choices=[('Tunai', 'Tunai (Cash)'), ('Non-Tunai', 'Non-Tunai (QRIS)')], default='Tunai', max_length=50)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('nama_penerima', models.CharField(blank=True, max_length=100, null=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pesanan', models.PositiveIntegerField(default=1)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Subtotal')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.produk')),
            ],
        ),
    ]
