# Generated by Django 5.0.7 on 2026-04-01 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaksi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transaksi.transaksi'),
        ),
    ]
