# Generated by Django 5.0.7 on 2026-04-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='kode_pesanan',
            new_name='kode_transaksi',
        ),
    ]
