# Generated by Django 5.0.7 on 2026-04-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_rename_kode_pesanan_transaksi_kode_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(choices=[('Tunai', 'Tunai (Cash)'), ('Transfer', 'Transfer (Bank / QRIS)')], default='Tunai', max_length=50),
        ),
    ]
