# Generated by Django 5.0.7 on 2026-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0004_alter_transaksi_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporanpenjualan',
            options={'verbose_name': 'Laporan Penjualan', 'verbose_name_plural': 'Laporan Penjualan'},
        ),
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='tanggal_akhir',
            field=models.DateField(help_text='Catatan: Input sesuai tanggal lokal Anda.', verbose_name='Sampai Tanggal'),
        ),
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='tanggal_laporan',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pembuatan'),
        ),
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='tanggal_mulai',
            field=models.DateField(help_text='Catatan: Input sesuai tanggal lokal Anda.', verbose_name='Dari Tanggal'),
        ),
    ]
