# Generated by Django 5.0.7 on 2026-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0005_alter_laporanpenjualan_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laporanpenjualan',
            old_name='pendapatan_transfer',
            new_name='pendapatan_non_tunai',
        ),
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Habis', 'Habis')], default='Tersedia', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(choices=[('Tunai', 'Tunai (Cash)'), ('Non-Tunai', 'Non-Tunai (Transfer / QRIS)')], default='Tunai', max_length=50),
        ),
    ]
