# Generated by Django 5.0.7 on 2026-04-12 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0006_rename_pendapatan_transfer_laporanpenjualan_pendapatan_non_tunai_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Sangat Buruk'), (2, '2 - Buruk'), (3, '3 - Cukup'), (4, '4 - Bagus'), (5, '5 - Sangat Puas')], default=5)),
                ('komentar', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='transaksi.produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
