# Generated by Django 5.0.7 on 2026-04-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0007_ulasan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('tipe', models.CharField(choices=[('MASUK', 'Masuk'), ('KELUAR', 'Keluar')], max_length=10)),
                ('keterangan', models.CharField(max_length=255)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.produk')),
            ],
        ),
    ]
