# Generated by Django 5.0.7 on 2026-04-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0008_mutasistok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutasiStok',
        ),
    ]
