# Generated by Django 5.0.7 on 2026-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0009_delete_mutasistok'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='foto_bukti',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_penerimaan/'),
        ),
    ]
