# Generated by Django 5.0.7 on 2026-05-30 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0010_transaksi_foto_bukti'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('tipe', models.CharField(choices=[('MASUK', 'Masuk'), ('KELUAR', 'Keluar')], max_length=6)),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutasi', to='transaksi.produk')),
            ],
        ),
    ]
