# Generated by Django 5.0.7 on 2026-07-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0011_mutasistok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wilayah', models.CharField(max_length=100)),
                ('biaya_ongkir', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Master Wilayah Ongkir',
                'verbose_name_plural': 'Master Wilayah Ongkir',
            },
        ),
        migrations.AddField(
            model_name='transaksi',
            name='biaya_kemasan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biaya Kemasan'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='biaya_layanan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biaya Layanan'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='biaya_ongkir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biaya Ongkir'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='total_pembayaran',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Akhir Pembayaran'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Harga Produk'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='wilayah_tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transaksi.wilayah', verbose_name='Wilayah Tujuan'),
        ),
    ]
