# Generated by Django 5.0.7 on 2026-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0012_wilayah_transaksi_biaya_kemasan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutasistok',
            name='tipe',
            field=models.CharField(choices=[('AWAL', 'Stok Awal'), ('MASUK', 'Masuk (Restock)'), ('KELUAR', 'Keluar (Penjualan)'), ('RUSAK', 'Barang Rusak (Es Mencair)'), ('REJECT', 'Stock Reject (Gagal Sortir)')], max_length=7),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.PositiveIntegerField(default=0, help_text='Stok Fisik Saat Ini'),
        ),
    ]
